// @generated by buffa-codegen. DO NOT EDIT.
// source: pumpfun/v1/launches.proto

#[derive(Clone, PartialEq, Default)]
pub struct Launch {
    /// Field 1: `slot`
    pub slot: u64,
    /// Field 2: `signature`
    pub signature: ::buffa::alloc::string::String,
    /// Field 3: `mint`
    pub mint: ::buffa::alloc::string::String,
    /// Field 4: `name`
    pub name: ::buffa::alloc::string::String,
    /// Field 5: `symbol`
    pub symbol: ::buffa::alloc::string::String,
    /// Field 6: `creator`
    pub creator: ::buffa::alloc::string::String,
    /// Field 7: `initial_virtual_sol_reserves`
    pub initial_virtual_sol_reserves: ::buffa::alloc::string::String,
    /// Field 8: `initial_virtual_token_reserves`
    pub initial_virtual_token_reserves: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for Launch {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Launch")
            .field("slot", &self.slot)
            .field("signature", &self.signature)
            .field("mint", &self.mint)
            .field("name", &self.name)
            .field("symbol", &self.symbol)
            .field("creator", &self.creator)
            .field("initial_virtual_sol_reserves", &self.initial_virtual_sol_reserves)
            .field(
                "initial_virtual_token_reserves",
                &self.initial_virtual_token_reserves,
            )
            .finish()
    }
}
impl Launch {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/pumpfun.v1.Launch";
}
::buffa::impl_default_instance!(Launch);
impl ::buffa::MessageName for Launch {
    const PACKAGE: &'static str = "pumpfun.v1";
    const NAME: &'static str = "Launch";
    const FULL_NAME: &'static str = "pumpfun.v1.Launch";
    const TYPE_URL: &'static str = "type.googleapis.com/pumpfun.v1.Launch";
}
impl ::buffa::Message for Launch {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.slot) as u64;
        }
        if !self.signature.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.signature) as u64;
        }
        if !self.mint.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.mint) as u64;
        }
        if !self.name.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.name) as u64;
        }
        if !self.symbol.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.symbol) as u64;
        }
        if !self.creator.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.creator) as u64;
        }
        if !self.initial_virtual_sol_reserves.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(
                        &self.initial_virtual_sol_reserves,
                    ) as u64;
        }
        if !self.initial_virtual_token_reserves.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(
                        &self.initial_virtual_token_reserves,
                    ) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.slot != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.slot, buf);
        }
        if !self.signature.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.signature, buf);
        }
        if !self.mint.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.mint, buf);
        }
        if !self.name.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.name, buf);
        }
        if !self.symbol.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.symbol, buf);
        }
        if !self.creator.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.creator, buf);
        }
        if !self.initial_virtual_sol_reserves.is_empty() {
            ::buffa::types::put_string_field(
                7u32,
                &self.initial_virtual_sol_reserves,
                buf,
            );
        }
        if !self.initial_virtual_token_reserves.is_empty() {
            ::buffa::types::put_string_field(
                8u32,
                &self.initial_virtual_token_reserves,
                buf,
            );
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.slot = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.signature, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.mint, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.name, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.symbol, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.creator, buf)?;
            }
            7u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    &mut self.initial_virtual_sol_reserves,
                    buf,
                )?;
            }
            8u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(
                    &mut self.initial_virtual_token_reserves,
                    buf,
                )?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.slot = 0u64;
        self.signature.clear();
        self.mint.clear();
        self.name.clear();
        self.symbol.clear();
        self.creator.clear();
        self.initial_virtual_sol_reserves.clear();
        self.initial_virtual_token_reserves.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Launches {
    /// Field 1: `launches`
    pub launches: ::buffa::alloc::vec::Vec<Launch>,
}
impl ::core::fmt::Debug for Launches {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Launches").field("launches", &self.launches).finish()
    }
}
impl Launches {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/pumpfun.v1.Launches";
}
::buffa::impl_default_instance!(Launches);
impl ::buffa::MessageName for Launches {
    const PACKAGE: &'static str = "pumpfun.v1";
    const NAME: &'static str = "Launches";
    const FULL_NAME: &'static str = "pumpfun.v1.Launches";
    const TYPE_URL: &'static str = "type.googleapis.com/pumpfun.v1.Launches";
}
impl ::buffa::Message for Launches {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.launches {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.launches {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.launches.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.launches.clear();
    }
}
