// @generated by buffa-codegen. DO NOT EDIT.

include!("pumpfun.v1.launches.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("pumpfun.v1.launches.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("pumpfun.v1.launches.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::LaunchView;
#[doc(inline)]
pub use self::__buffa::view::LaunchOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::LaunchLazyView;
#[doc(inline)]
pub use self::__buffa::view::LaunchesView;
#[doc(inline)]
pub use self::__buffa::view::LaunchesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::LaunchesLazyView;
