// @generated by buffa-codegen. DO NOT EDIT.
// source: marinade/deposit/v1/deposits.proto

#[derive(Clone, PartialEq, Default)]
pub struct Deposit {
    /// Field 1: `slot`
    pub slot: u64,
    /// Field 2: `signature`
    pub signature: ::buffa::alloc::string::String,
    /// Field 3: `user_wallet`
    pub user_wallet: ::buffa::alloc::string::String,
    /// Field 4: `sol_amount`
    pub sol_amount: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for Deposit {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Deposit")
            .field("slot", &self.slot)
            .field("signature", &self.signature)
            .field("user_wallet", &self.user_wallet)
            .field("sol_amount", &self.sol_amount)
            .finish()
    }
}
impl Deposit {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/marinade.deposit.v1.Deposit";
}
::buffa::impl_default_instance!(Deposit);
impl ::buffa::MessageName for Deposit {
    const PACKAGE: &'static str = "marinade.deposit.v1";
    const NAME: &'static str = "Deposit";
    const FULL_NAME: &'static str = "marinade.deposit.v1.Deposit";
    const TYPE_URL: &'static str = "type.googleapis.com/marinade.deposit.v1.Deposit";
}
impl ::buffa::Message for Deposit {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.slot) as u64;
        }
        if !self.signature.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.signature) as u64;
        }
        if !self.user_wallet.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.user_wallet) as u64;
        }
        if !self.sol_amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.sol_amount) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.slot != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.slot, buf);
        }
        if !self.signature.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.signature, buf);
        }
        if !self.user_wallet.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.user_wallet, buf);
        }
        if !self.sol_amount.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.sol_amount, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.slot = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.signature, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.user_wallet, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.sol_amount, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.slot = 0u64;
        self.signature.clear();
        self.user_wallet.clear();
        self.sol_amount.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Deposits {
    /// Field 1: `deposits`
    pub deposits: ::buffa::alloc::vec::Vec<Deposit>,
}
impl ::core::fmt::Debug for Deposits {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Deposits").field("deposits", &self.deposits).finish()
    }
}
impl Deposits {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/marinade.deposit.v1.Deposits";
}
::buffa::impl_default_instance!(Deposits);
impl ::buffa::MessageName for Deposits {
    const PACKAGE: &'static str = "marinade.deposit.v1";
    const NAME: &'static str = "Deposits";
    const FULL_NAME: &'static str = "marinade.deposit.v1.Deposits";
    const TYPE_URL: &'static str = "type.googleapis.com/marinade.deposit.v1.Deposits";
}
impl ::buffa::Message for Deposits {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.deposits {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.deposits {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.deposits.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.deposits.clear();
    }
}
