// @generated by buffa-codegen. DO NOT EDIT.

include!("sol.v1.sol.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("sol.v1.sol.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("sol.v1.sol.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::TransferView;
#[doc(inline)]
pub use self::__buffa::view::TransferOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransferLazyView;
#[doc(inline)]
pub use self::__buffa::view::TransfersView;
#[doc(inline)]
pub use self::__buffa::view::TransfersOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TransfersLazyView;
