// @generated by buffa-codegen. DO NOT EDIT.
// source: sol/v1/sol.proto

#[derive(Clone, PartialEq, Default)]
pub struct Transfer {
    /// Field 1: `slot`
    pub slot: u64,
    /// Field 2: `tx_signature`
    pub tx_signature: ::buffa::alloc::string::String,
    /// Field 3: `source`
    pub source: ::buffa::alloc::string::String,
    /// Field 4: `destination`
    pub destination: ::buffa::alloc::string::String,
    /// Field 5: `amount`
    pub amount: ::buffa::alloc::string::String,
    /// Field 6: `authority`
    pub authority: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for Transfer {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Transfer")
            .field("slot", &self.slot)
            .field("tx_signature", &self.tx_signature)
            .field("source", &self.source)
            .field("destination", &self.destination)
            .field("amount", &self.amount)
            .field("authority", &self.authority)
            .finish()
    }
}
impl Transfer {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sol.v1.Transfer";
}
::buffa::impl_default_instance!(Transfer);
impl ::buffa::MessageName for Transfer {
    const PACKAGE: &'static str = "sol.v1";
    const NAME: &'static str = "Transfer";
    const FULL_NAME: &'static str = "sol.v1.Transfer";
    const TYPE_URL: &'static str = "type.googleapis.com/sol.v1.Transfer";
}
impl ::buffa::Message for Transfer {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.slot != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.slot) as u64;
        }
        if !self.tx_signature.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_signature) as u64;
        }
        if !self.source.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.source) as u64;
        }
        if !self.destination.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.destination) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if !self.authority.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.authority) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.slot != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.slot, buf);
        }
        if !self.tx_signature.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.tx_signature, buf);
        }
        if !self.source.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.source, buf);
        }
        if !self.destination.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.destination, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.amount, buf);
        }
        if !self.authority.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.authority, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.slot = ::buffa::types::decode_uint64(buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.tx_signature, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.source, buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.destination, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.amount, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.authority, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.slot = 0u64;
        self.tx_signature.clear();
        self.source.clear();
        self.destination.clear();
        self.amount.clear();
        self.authority.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct Transfers {
    /// Field 1: `transfers`
    pub transfers: ::buffa::alloc::vec::Vec<Transfer>,
}
impl ::core::fmt::Debug for Transfers {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Transfers").field("transfers", &self.transfers).finish()
    }
}
impl Transfers {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/sol.v1.Transfers";
}
::buffa::impl_default_instance!(Transfers);
impl ::buffa::MessageName for Transfers {
    const PACKAGE: &'static str = "sol.v1";
    const NAME: &'static str = "Transfers";
    const FULL_NAME: &'static str = "sol.v1.Transfers";
    const TYPE_URL: &'static str = "type.googleapis.com/sol.v1.Transfers";
}
impl ::buffa::Message for Transfers {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.transfers {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.transfers {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.transfers.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.transfers.clear();
    }
}
