// @generated
// This file was @generated by `substreams-ethereum-abigen`. Do not edit it by hand.

/// Contract's functions.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod functions {
    #[derive(Debug, Clone, PartialEq)]
    pub struct Token0 {}
    impl Token0 {
        const METHOD_ID: [u8; 4] = [13u8, 254u8, 22u8, 129u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Ok(Self {})
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 0usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 0usize);
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Vec<u8>, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Ok(substreams_ethereum::abi::read_address(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<Vec<u8>> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for Token0 {
        const NAME: &'static str = "token0";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<Vec<u8>> for Token0 {
        fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Self::output(data)
        }
    }
    #[derive(Debug, Clone, PartialEq)]
    pub struct Token1 {}
    impl Token1 {
        const METHOD_ID: [u8; 4] = [210u8, 18u8, 32u8, 167u8];
        pub fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Ok(Self {})
        }
        pub fn encode(&self) -> Vec<u8> {
            let mut out: Vec<u8> = Vec::with_capacity(4 + 0usize);
            out.extend(Self::METHOD_ID);
            let base = substreams_ethereum::abi::reserve_head(&mut out, 0usize);
            out
        }
        pub fn output_call(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Vec<u8>, String> {
            Self::output(call.return_data.as_ref())
        }
        pub fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Ok(substreams_ethereum::abi::read_address(data, 0, "output")?)
        }
        pub fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            match call.input.get(0..4) {
                Some(signature) => Self::METHOD_ID == signature,
                None => false,
            }
        }
        pub fn call(&self, address: Vec<u8>) -> Option<Vec<u8>> {
            use substreams_ethereum::pb::eth::rpc;
            let rpc_calls = rpc::RpcCalls {
                calls: vec![rpc::RpcCall { to_addr : address, data : self.encode(), }],
            };
            let responses = substreams_ethereum::rpc::eth_call(&rpc_calls).responses;
            let response = responses.get(0).expect("one response should have existed");
            if response.failed {
                return None;
            }
            match Self::output(response.raw.as_ref()) {
                Ok(data) => Some(data),
                Err(err) => {
                    use substreams_ethereum::Function;
                    substreams::log::info!(
                        "Call output for function `{}` failed to decode with error: {}",
                        Self::NAME, err
                    );
                    None
                }
            }
        }
    }
    impl substreams_ethereum::Function for Token1 {
        const NAME: &'static str = "token1";
        fn match_call(call: &substreams_ethereum::pb::eth::v2::Call) -> bool {
            Self::match_call(call)
        }
        fn decode(
            call: &substreams_ethereum::pb::eth::v2::Call,
        ) -> Result<Self, String> {
            Self::decode(call)
        }
        fn encode(&self) -> Vec<u8> {
            self.encode()
        }
    }
    impl substreams_ethereum::rpc::RPCDecodable<Vec<u8>> for Token1 {
        fn output(data: &[u8]) -> Result<Vec<u8>, String> {
            Self::output(data)
        }
    }
}
/// Contract's events.
#[allow(dead_code, unused_imports, unused_variables)]
pub mod events {
    #[derive(Debug, Clone, PartialEq)]
    pub struct Swap {
        pub sender: Vec<u8>,
        pub recipient: Vec<u8>,
        pub amount0: substreams::scalar::BigInt,
        pub amount1: substreams::scalar::BigInt,
        pub sqrt_price_x96: substreams::scalar::BigInt,
        pub liquidity: substreams::scalar::BigInt,
        pub tick: substreams::scalar::BigInt,
    }
    impl Swap {
        const TOPIC_ID: [u8; 32] = [
            196u8,
            32u8,
            121u8,
            249u8,
            74u8,
            99u8,
            80u8,
            215u8,
            230u8,
            35u8,
            95u8,
            41u8,
            23u8,
            73u8,
            36u8,
            249u8,
            40u8,
            204u8,
            42u8,
            200u8,
            24u8,
            235u8,
            100u8,
            254u8,
            216u8,
            0u8,
            78u8,
            17u8,
            95u8,
            188u8,
            202u8,
            103u8,
        ];
        pub fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            if log.topic_count() != 3usize {
                return false;
            }
            if log.data().len() != 160usize {
                return false;
            }
            return log.topic(0).expect("bounds already checked") == Self::TOPIC_ID;
        }
        pub fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            if log.topic_count() != 3usize {
                return Err(
                    format!(
                        "unexpected topic count, expected {}, got {}", 3usize, log
                        .topic_count()
                    ),
                );
            }
            if log.data().len() < 160usize {
                return Err(
                    format!(
                        "data too short, expected at least {}, got {}", 160usize, log
                        .data().len()
                    ),
                );
            }
            Ok(Self {
                sender: substreams_ethereum::abi::read_address(
                    log.topic(1usize).expect("bounds already checked"),
                    0,
                    "sender",
                )?,
                recipient: substreams_ethereum::abi::read_address(
                    log.topic(2usize).expect("bounds already checked"),
                    0,
                    "recipient",
                )?,
                amount0: substreams_ethereum::abi::read_int(log.data(), 0, "amount0")?,
                amount1: substreams_ethereum::abi::read_int(log.data(), 32, "amount1")?,
                sqrt_price_x96: substreams_ethereum::abi::read_uint(
                    log.data(),
                    64,
                    "sqrt_price_x96",
                )?,
                liquidity: substreams_ethereum::abi::read_uint(
                    log.data(),
                    96,
                    "liquidity",
                )?,
                tick: substreams_ethereum::abi::read_int(log.data(), 128, "tick")?,
            })
        }
    }
    impl substreams_ethereum::Event for Swap {
        const NAME: &'static str = "Swap";
        fn match_log<L: substreams_ethereum::LogLike>(log: &L) -> bool {
            Self::match_log(log)
        }
        fn decode<L: substreams_ethereum::LogLike>(log: &L) -> Result<Self, String> {
            Self::decode(log)
        }
    }
}