// @generated by buffa-codegen. DO NOT EDIT.

include!("uniswap_v2.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("uniswap_v2.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("uniswap_v2.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::PoolEventsView;
#[doc(inline)]
pub use self::__buffa::view::PoolEventsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PoolEventsLazyView;
#[doc(inline)]
pub use self::__buffa::view::PoolSwapEventView;
#[doc(inline)]
pub use self::__buffa::view::PoolSwapEventOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PoolSwapEventLazyView;
#[doc(inline)]
pub use self::__buffa::view::SwapsView;
#[doc(inline)]
pub use self::__buffa::view::SwapsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::SwapsLazyView;
#[doc(inline)]
pub use self::__buffa::view::SwapView;
#[doc(inline)]
pub use self::__buffa::view::SwapOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::SwapLazyView;
