// @generated by buffa-codegen. DO NOT EDIT.
// source: usdc_transfers.proto

#[derive(Clone, Debug, Default)]
pub struct UsdcTransfersView<'a> {
    /// Field 1: `transfers`
    pub transfers: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::UsdcTransferView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for UsdcTransfersView<'a> {
    type Owned = super::super::UsdcTransfers;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::UsdcTransferView,
                    >(),
                )?;
                view.transfers
                    .push(
                        <super::super::__buffa::view::UsdcTransferView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::UsdcTransfers, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::UsdcTransfers, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::UsdcTransfers {
            transfers: self
                .transfers
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for UsdcTransfersView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.transfers {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.transfers {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for UsdcTransfersView<'a> {
    const PACKAGE: &'static str = "usdc.transfers.v1";
    const NAME: &'static str = "UsdcTransfers";
    const FULL_NAME: &'static str = "usdc.transfers.v1.UsdcTransfers";
    const TYPE_URL: &'static str = "type.googleapis.com/usdc.transfers.v1.UsdcTransfers";
}
::buffa::impl_default_view_instance!(UsdcTransfersView);
::buffa::impl_view_reborrow!(UsdcTransfersView);
/** Self-contained, `'static` owned view of a `UsdcTransfers` message.

 Wraps [`::buffa::OwnedView`]`<`[`UsdcTransfersView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`UsdcTransfersView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct UsdcTransfersOwnedView(::buffa::OwnedView<UsdcTransfersView<'static>>);
impl UsdcTransfersOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            UsdcTransfersOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            UsdcTransfersOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::UsdcTransfers,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            UsdcTransfersOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`UsdcTransfersView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &UsdcTransfersView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::UsdcTransfers {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `transfers`
    #[must_use]
    pub fn transfers(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::UsdcTransferView<'_>> {
        &self.0.reborrow().transfers
    }
}
impl ::core::convert::From<::buffa::OwnedView<UsdcTransfersView<'static>>>
for UsdcTransfersOwnedView {
    fn from(inner: ::buffa::OwnedView<UsdcTransfersView<'static>>) -> Self {
        UsdcTransfersOwnedView(inner)
    }
}
impl ::core::convert::From<UsdcTransfersOwnedView>
for ::buffa::OwnedView<UsdcTransfersView<'static>> {
    fn from(wrapper: UsdcTransfersOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<UsdcTransfersView<'static>>>
for UsdcTransfersOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<UsdcTransfersView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::UsdcTransfers {
    type View<'a> = UsdcTransfersView<'a>;
    type ViewHandle = UsdcTransfersOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct UsdcTransferView<'a> {
    /// Field 1: `tx_hash`
    pub tx_hash: &'a str,
    /// Field 2: `log_index`
    pub log_index: u64,
    /// Field 3: `from`
    pub from: &'a str,
    /// Field 4: `to`
    pub to: &'a str,
    /// Field 5: `amount`
    pub amount: &'a str,
    /// Field 6: `block_number`
    pub block_number: u64,
}
impl<'a> ::buffa::MessageView<'a> for UsdcTransferView<'a> {
    type Owned = super::super::UsdcTransfer;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.tx_hash = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.log_index = ::buffa::types::decode_uint64(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.from = ::buffa::types::borrow_str(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.to = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.block_number = ::buffa::types::decode_uint64(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::UsdcTransfer, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::UsdcTransfer, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::UsdcTransfer {
            tx_hash: self.tx_hash.to_string(),
            log_index: self.log_index,
            from: self.from.to_string(),
            to: self.to.to_string(),
            amount: self.amount.to_string(),
            block_number: self.block_number,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for UsdcTransferView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.tx_hash.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.tx_hash) as u64;
        }
        if self.log_index != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.log_index) as u64;
        }
        if !self.from.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.from) as u64;
        }
        if !self.to.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.to) as u64;
        }
        if !self.amount.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount) as u64;
        }
        if self.block_number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.block_number) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.tx_hash.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.tx_hash, buf);
        }
        if self.log_index != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.log_index, buf);
        }
        if !self.from.is_empty() {
            ::buffa::types::put_string_field(3u32, &self.from, buf);
        }
        if !self.to.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.to, buf);
        }
        if !self.amount.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.amount, buf);
        }
        if self.block_number != 0u64 {
            ::buffa::types::put_uint64_field(6u32, self.block_number, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for UsdcTransferView<'a> {
    const PACKAGE: &'static str = "usdc.transfers.v1";
    const NAME: &'static str = "UsdcTransfer";
    const FULL_NAME: &'static str = "usdc.transfers.v1.UsdcTransfer";
    const TYPE_URL: &'static str = "type.googleapis.com/usdc.transfers.v1.UsdcTransfer";
}
::buffa::impl_default_view_instance!(UsdcTransferView);
::buffa::impl_view_reborrow!(UsdcTransferView);
/** Self-contained, `'static` owned view of a `UsdcTransfer` message.

 Wraps [`::buffa::OwnedView`]`<`[`UsdcTransferView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`UsdcTransferView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct UsdcTransferOwnedView(::buffa::OwnedView<UsdcTransferView<'static>>);
impl UsdcTransferOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            UsdcTransferOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            UsdcTransferOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::UsdcTransfer,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            UsdcTransferOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`UsdcTransferView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &UsdcTransferView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::UsdcTransfer {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `tx_hash`
    #[must_use]
    pub fn tx_hash(&self) -> &'_ str {
        self.0.reborrow().tx_hash
    }
    /// Field 2: `log_index`
    #[must_use]
    pub fn log_index(&self) -> u64 {
        self.0.reborrow().log_index
    }
    /// Field 3: `from`
    #[must_use]
    pub fn from(&self) -> &'_ str {
        self.0.reborrow().from
    }
    /// Field 4: `to`
    #[must_use]
    pub fn to(&self) -> &'_ str {
        self.0.reborrow().to
    }
    /// Field 5: `amount`
    #[must_use]
    pub fn amount(&self) -> &'_ str {
        self.0.reborrow().amount
    }
    /// Field 6: `block_number`
    #[must_use]
    pub fn block_number(&self) -> u64 {
        self.0.reborrow().block_number
    }
}
impl ::core::convert::From<::buffa::OwnedView<UsdcTransferView<'static>>>
for UsdcTransferOwnedView {
    fn from(inner: ::buffa::OwnedView<UsdcTransferView<'static>>) -> Self {
        UsdcTransferOwnedView(inner)
    }
}
impl ::core::convert::From<UsdcTransferOwnedView>
for ::buffa::OwnedView<UsdcTransferView<'static>> {
    fn from(wrapper: UsdcTransferOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<UsdcTransferView<'static>>>
for UsdcTransferOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<UsdcTransferView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::UsdcTransfer {
    type View<'a> = UsdcTransferView<'a>;
    type ViewHandle = UsdcTransferOwnedView;
}
