// @generated by buffa-codegen. DO NOT EDIT.
// source: stats.proto

#[derive(Clone, Debug, Default)]
pub struct BlockStatsView<'a> {
    /// Field 1: `number`
    pub number: u64,
    /// Field 2: `tx_count`
    pub tx_count: u64,
    /// Field 3: `gas_used`
    pub gas_used: u64,
    /// Field 4: `base_fee`
    pub base_fee: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for BlockStatsView<'a> {
    type Owned = super::super::BlockStats;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.number = ::buffa::types::decode_uint64(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.tx_count = ::buffa::types::decode_uint64(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.gas_used = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.base_fee = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::BlockStats, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::BlockStats, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::BlockStats {
            number: self.number,
            tx_count: self.tx_count,
            gas_used: self.gas_used,
            base_fee: self.base_fee.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for BlockStatsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if self.number != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.number) as u64;
        }
        if self.tx_count != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.tx_count) as u64;
        }
        if self.gas_used != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.gas_used) as u64;
        }
        if !self.base_fee.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.base_fee) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if self.number != 0u64 {
            ::buffa::types::put_uint64_field(1u32, self.number, buf);
        }
        if self.tx_count != 0u64 {
            ::buffa::types::put_uint64_field(2u32, self.tx_count, buf);
        }
        if self.gas_used != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.gas_used, buf);
        }
        if !self.base_fee.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.base_fee, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for BlockStatsView<'a> {
    const PACKAGE: &'static str = "eth.stats.v1";
    const NAME: &'static str = "BlockStats";
    const FULL_NAME: &'static str = "eth.stats.v1.BlockStats";
    const TYPE_URL: &'static str = "type.googleapis.com/eth.stats.v1.BlockStats";
}
::buffa::impl_default_view_instance!(BlockStatsView);
::buffa::impl_view_reborrow!(BlockStatsView);
/** Self-contained, `'static` owned view of a `BlockStats` message.

 Wraps [`::buffa::OwnedView`]`<`[`BlockStatsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`BlockStatsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct BlockStatsOwnedView(::buffa::OwnedView<BlockStatsView<'static>>);
impl BlockStatsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockStatsOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockStatsOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::BlockStats,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            BlockStatsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`BlockStatsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &BlockStatsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::BlockStats {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `number`
    #[must_use]
    pub fn number(&self) -> u64 {
        self.0.reborrow().number
    }
    /// Field 2: `tx_count`
    #[must_use]
    pub fn tx_count(&self) -> u64 {
        self.0.reborrow().tx_count
    }
    /// Field 3: `gas_used`
    #[must_use]
    pub fn gas_used(&self) -> u64 {
        self.0.reborrow().gas_used
    }
    /// Field 4: `base_fee`
    #[must_use]
    pub fn base_fee(&self) -> &'_ str {
        self.0.reborrow().base_fee
    }
}
impl ::core::convert::From<::buffa::OwnedView<BlockStatsView<'static>>>
for BlockStatsOwnedView {
    fn from(inner: ::buffa::OwnedView<BlockStatsView<'static>>) -> Self {
        BlockStatsOwnedView(inner)
    }
}
impl ::core::convert::From<BlockStatsOwnedView>
for ::buffa::OwnedView<BlockStatsView<'static>> {
    fn from(wrapper: BlockStatsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<BlockStatsView<'static>>>
for BlockStatsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<BlockStatsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::BlockStats {
    type View<'a> = BlockStatsView<'a>;
    type ViewHandle = BlockStatsOwnedView;
}
