// @generated by buffa-codegen. DO NOT EDIT.

include!("dex_volume.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("dex_volume.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("dex_volume.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::SwapVolumeView;
#[doc(inline)]
pub use self::__buffa::view::SwapVolumeOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::SwapVolumeLazyView;
#[doc(inline)]
pub use self::__buffa::view::SwapVolumesView;
#[doc(inline)]
pub use self::__buffa::view::SwapVolumesOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::SwapVolumesLazyView;
#[doc(inline)]
pub use self::__buffa::view::TokenPairView;
#[doc(inline)]
pub use self::__buffa::view::TokenPairOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::TokenPairLazyView;
#[doc(inline)]
pub use self::__buffa::view::PoolTokenEntryView;
#[doc(inline)]
pub use self::__buffa::view::PoolTokenEntryOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PoolTokenEntryLazyView;
#[doc(inline)]
pub use self::__buffa::view::PoolTokenPairsView;
#[doc(inline)]
pub use self::__buffa::view::PoolTokenPairsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::PoolTokenPairsLazyView;
