// @generated by buffa-codegen. DO NOT EDIT.
// source: dex_volume.proto

/// Emitted by map_v2_swaps / map_v3_swaps: one SwapVolume per Swap log in the block.
/// Carries enough info for the store to bucket by (protocol, pool, day).
#[derive(Clone, PartialEq, Default)]
pub struct SwapVolume {
    /// Protocol: "v2" or "v3"
    ///
    /// Field 1: `protocol`
    pub protocol: ::buffa::alloc::string::String,
    /// Pool address, lowercase hex with 0x prefix
    ///
    /// Field 2: `pool_address`
    pub pool_address: ::buffa::alloc::string::String,
    /// Unix day bucket: block_timestamp / 86400
    ///
    /// Field 3: `day_bucket`
    pub day_bucket: u64,
    /// |amount1| in raw token units (unsigned bigint as decimal string)
    ///
    /// Field 4: `amount1_abs`
    pub amount1_abs: ::buffa::alloc::string::String,
    /// Token1 decimals (for display / volume scaling)
    ///
    /// Field 5: `token1_decimals`
    pub token1_decimals: u32,
    /// Token1 symbol (for labelling)
    ///
    /// Field 6: `token1_symbol`
    pub token1_symbol: ::buffa::alloc::string::String,
}
impl ::core::fmt::Debug for SwapVolume {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SwapVolume")
            .field("protocol", &self.protocol)
            .field("pool_address", &self.pool_address)
            .field("day_bucket", &self.day_bucket)
            .field("amount1_abs", &self.amount1_abs)
            .field("token1_decimals", &self.token1_decimals)
            .field("token1_symbol", &self.token1_symbol)
            .finish()
    }
}
impl SwapVolume {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.SwapVolume";
}
::buffa::impl_default_instance!(SwapVolume);
impl ::buffa::MessageName for SwapVolume {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "SwapVolume";
    const FULL_NAME: &'static str = "dex.volume.v1.SwapVolume";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.SwapVolume";
}
impl ::buffa::Message for SwapVolume {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.protocol.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.protocol) as u64;
        }
        if !self.pool_address.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.pool_address) as u64;
        }
        if self.day_bucket != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.day_bucket) as u64;
        }
        if !self.amount1_abs.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount1_abs) as u64;
        }
        if self.token1_decimals != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.token1_decimals) as u64;
        }
        if !self.token1_symbol.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.token1_symbol) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.protocol.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.protocol, buf);
        }
        if !self.pool_address.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.pool_address, buf);
        }
        if self.day_bucket != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.day_bucket, buf);
        }
        if !self.amount1_abs.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount1_abs, buf);
        }
        if self.token1_decimals != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.token1_decimals, buf);
        }
        if !self.token1_symbol.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.token1_symbol, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.protocol, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.pool_address, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.day_bucket = ::buffa::types::decode_uint64(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.amount1_abs, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.token1_decimals = ::buffa::types::decode_uint32(buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.token1_symbol, buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.protocol.clear();
        self.pool_address.clear();
        self.day_bucket = 0u64;
        self.amount1_abs.clear();
        self.token1_decimals = 0u32;
        self.token1_symbol.clear();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct SwapVolumes {
    /// Field 1: `swaps`
    pub swaps: ::buffa::alloc::vec::Vec<SwapVolume>,
}
impl ::core::fmt::Debug for SwapVolumes {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("SwapVolumes").field("swaps", &self.swaps).finish()
    }
}
impl SwapVolumes {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.SwapVolumes";
}
::buffa::impl_default_instance!(SwapVolumes);
impl ::buffa::MessageName for SwapVolumes {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "SwapVolumes";
    const FULL_NAME: &'static str = "dex.volume.v1.SwapVolumes";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.SwapVolumes";
}
impl ::buffa::Message for SwapVolumes {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.swaps {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.swaps {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.swaps.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.swaps.clear();
    }
}
/// Per-pool token metadata, cached in a store keyed by pool address
/// (separate store keys per protocol to avoid cross-protocol collision)
#[derive(Clone, PartialEq, Default)]
pub struct TokenPair {
    /// Field 1: `token0_address`
    pub token0_address: ::buffa::alloc::string::String,
    /// Field 2: `token0_symbol`
    pub token0_symbol: ::buffa::alloc::string::String,
    /// Field 3: `token0_decimals`
    pub token0_decimals: u32,
    /// Field 4: `token1_address`
    pub token1_address: ::buffa::alloc::string::String,
    /// Field 5: `token1_symbol`
    pub token1_symbol: ::buffa::alloc::string::String,
    /// Field 6: `token1_decimals`
    pub token1_decimals: u32,
}
impl ::core::fmt::Debug for TokenPair {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("TokenPair")
            .field("token0_address", &self.token0_address)
            .field("token0_symbol", &self.token0_symbol)
            .field("token0_decimals", &self.token0_decimals)
            .field("token1_address", &self.token1_address)
            .field("token1_symbol", &self.token1_symbol)
            .field("token1_decimals", &self.token1_decimals)
            .finish()
    }
}
impl TokenPair {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.TokenPair";
}
::buffa::impl_default_instance!(TokenPair);
impl ::buffa::MessageName for TokenPair {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "TokenPair";
    const FULL_NAME: &'static str = "dex.volume.v1.TokenPair";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.TokenPair";
}
impl ::buffa::Message for TokenPair {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.token0_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.token0_address) as u64;
        }
        if !self.token0_symbol.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.token0_symbol) as u64;
        }
        if self.token0_decimals != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.token0_decimals) as u64;
        }
        if !self.token1_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.token1_address) as u64;
        }
        if !self.token1_symbol.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.token1_symbol) as u64;
        }
        if self.token1_decimals != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.token1_decimals) as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.token0_address.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.token0_address, buf);
        }
        if !self.token0_symbol.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.token0_symbol, buf);
        }
        if self.token0_decimals != 0u32 {
            ::buffa::types::put_uint32_field(3u32, self.token0_decimals, buf);
        }
        if !self.token1_address.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.token1_address, buf);
        }
        if !self.token1_symbol.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.token1_symbol, buf);
        }
        if self.token1_decimals != 0u32 {
            ::buffa::types::put_uint32_field(6u32, self.token1_decimals, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.token0_address, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.token0_symbol, buf)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.token0_decimals = ::buffa::types::decode_uint32(buf)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.token1_address, buf)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.token1_symbol, buf)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                self.token1_decimals = ::buffa::types::decode_uint32(buf)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.token0_address.clear();
        self.token0_symbol.clear();
        self.token0_decimals = 0u32;
        self.token1_address.clear();
        self.token1_symbol.clear();
        self.token1_decimals = 0u32;
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PoolTokenEntry {
    /// Key = "\<protocol\>:\<pool_address\>" to ensure per-protocol namespacing
    ///
    /// Field 1: `key`
    pub key: ::buffa::alloc::string::String,
    /// Field 2: `pair`
    pub pair: ::buffa::MessageField<TokenPair, ::buffa::Inline<TokenPair>>,
}
impl ::core::fmt::Debug for PoolTokenEntry {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PoolTokenEntry")
            .field("key", &self.key)
            .field("pair", &self.pair)
            .finish()
    }
}
impl PoolTokenEntry {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.PoolTokenEntry";
}
::buffa::impl_default_instance!(PoolTokenEntry);
impl ::buffa::MessageName for PoolTokenEntry {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "PoolTokenEntry";
    const FULL_NAME: &'static str = "dex.volume.v1.PoolTokenEntry";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.PoolTokenEntry";
}
impl ::buffa::Message for PoolTokenEntry {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.key.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.key) as u64;
        }
        if self.pair.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.pair.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.key.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.key, buf);
        }
        if self.pair.is_set() {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.pair.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::types::merge_string(&mut self.key, buf)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                ::buffa::Message::merge_length_delimited(
                    self.pair.get_or_insert_default(),
                    buf,
                    ctx,
                )?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.key.clear();
        self.pair = ::buffa::MessageField::none();
    }
}
#[derive(Clone, PartialEq, Default)]
pub struct PoolTokenPairs {
    /// Field 1: `entries`
    pub entries: ::buffa::alloc::vec::Vec<PoolTokenEntry>,
}
impl ::core::fmt::Debug for PoolTokenPairs {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("PoolTokenPairs").field("entries", &self.entries).finish()
    }
}
impl PoolTokenPairs {
    /// Protobuf type URL for this message, for use with `Any::pack` and
    /// `Any::unpack_if`.
    ///
    /// Format: `type.googleapis.com/<fully.qualified.TypeName>`
    pub const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.PoolTokenPairs";
}
::buffa::impl_default_instance!(PoolTokenPairs);
impl ::buffa::MessageName for PoolTokenPairs {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "PoolTokenPairs";
    const FULL_NAME: &'static str = "dex.volume.v1.PoolTokenPairs";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.PoolTokenPairs";
}
impl ::buffa::Message for PoolTokenPairs {
    /// Returns the total encoded size in bytes.
    ///
    /// Accumulates in `u64` (which cannot overflow for in-memory
    /// data) and saturates to `u32` at return, so a message whose
    /// encoded size exceeds the 2 GiB protobuf limit yields a value
    /// above [`::buffa::MAX_MESSAGE_BYTES`] that the encode entry
    /// points reject, never a silently wrapped size.
    #[allow(clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.entries {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.entries {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
    fn merge_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        buf: &mut impl ::buffa::bytes::Buf,
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<(), ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::bytes::Buf as _;
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let mut elem = ::core::default::Default::default();
                ctx.register_element_memory(
                    ::buffa::__private::element_footprint(&elem),
                )?;
                ::buffa::Message::merge_length_delimited(&mut elem, buf, ctx)?;
                self.entries.push(elem);
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, buf, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(())
    }
    fn clear(&mut self) {
        self.entries.clear();
    }
}
