// @generated by buffa-codegen. DO NOT EDIT.
// source: dex_volume.proto

/// Emitted by map_v2_swaps / map_v3_swaps: one SwapVolume per Swap log in the block.
/// Carries enough info for the store to bucket by (protocol, pool, day).
#[derive(Clone, Debug, Default)]
pub struct SwapVolumeView<'a> {
    /// Protocol: "v2" or "v3"
    ///
    /// Field 1: `protocol`
    pub protocol: &'a str,
    /// Pool address, lowercase hex with 0x prefix
    ///
    /// Field 2: `pool_address`
    pub pool_address: &'a str,
    /// Unix day bucket: block_timestamp / 86400
    ///
    /// Field 3: `day_bucket`
    pub day_bucket: u64,
    /// |amount1| in raw token units (unsigned bigint as decimal string)
    ///
    /// Field 4: `amount1_abs`
    pub amount1_abs: &'a str,
    /// Token1 decimals (for display / volume scaling)
    ///
    /// Field 5: `token1_decimals`
    pub token1_decimals: u32,
    /// Token1 symbol (for labelling)
    ///
    /// Field 6: `token1_symbol`
    pub token1_symbol: &'a str,
}
impl<'a> ::buffa::MessageView<'a> for SwapVolumeView<'a> {
    type Owned = super::super::SwapVolume;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.protocol = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.pool_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.day_bucket = ::buffa::types::decode_uint64(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.amount1_abs = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.token1_decimals = ::buffa::types::decode_uint32(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.token1_symbol = ::buffa::types::borrow_str(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::SwapVolume, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::SwapVolume, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::SwapVolume {
            protocol: self.protocol.to_string(),
            pool_address: self.pool_address.to_string(),
            day_bucket: self.day_bucket,
            amount1_abs: self.amount1_abs.to_string(),
            token1_decimals: self.token1_decimals,
            token1_symbol: self.token1_symbol.to_string(),
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for SwapVolumeView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.protocol.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.protocol) as u64;
        }
        if !self.pool_address.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.pool_address) as u64;
        }
        if self.day_bucket != 0u64 {
            size += 1u64 + ::buffa::types::uint64_encoded_len(self.day_bucket) as u64;
        }
        if !self.amount1_abs.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.amount1_abs) as u64;
        }
        if self.token1_decimals != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.token1_decimals) as u64;
        }
        if !self.token1_symbol.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.token1_symbol) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.protocol.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.protocol, buf);
        }
        if !self.pool_address.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.pool_address, buf);
        }
        if self.day_bucket != 0u64 {
            ::buffa::types::put_uint64_field(3u32, self.day_bucket, buf);
        }
        if !self.amount1_abs.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.amount1_abs, buf);
        }
        if self.token1_decimals != 0u32 {
            ::buffa::types::put_uint32_field(5u32, self.token1_decimals, buf);
        }
        if !self.token1_symbol.is_empty() {
            ::buffa::types::put_string_field(6u32, &self.token1_symbol, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for SwapVolumeView<'a> {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "SwapVolume";
    const FULL_NAME: &'static str = "dex.volume.v1.SwapVolume";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.SwapVolume";
}
::buffa::impl_default_view_instance!(SwapVolumeView);
::buffa::impl_view_reborrow!(SwapVolumeView);
/** Self-contained, `'static` owned view of a `SwapVolume` message.

 Wraps [`::buffa::OwnedView`]`<`[`SwapVolumeView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`SwapVolumeView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct SwapVolumeOwnedView(::buffa::OwnedView<SwapVolumeView<'static>>);
impl SwapVolumeOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SwapVolumeOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SwapVolumeOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::SwapVolume,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SwapVolumeOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`SwapVolumeView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &SwapVolumeView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::SwapVolume {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Protocol: "v2" or "v3"
    ///
    /// Field 1: `protocol`
    #[must_use]
    pub fn protocol(&self) -> &'_ str {
        self.0.reborrow().protocol
    }
    /// Pool address, lowercase hex with 0x prefix
    ///
    /// Field 2: `pool_address`
    #[must_use]
    pub fn pool_address(&self) -> &'_ str {
        self.0.reborrow().pool_address
    }
    /// Unix day bucket: block_timestamp / 86400
    ///
    /// Field 3: `day_bucket`
    #[must_use]
    pub fn day_bucket(&self) -> u64 {
        self.0.reborrow().day_bucket
    }
    /// |amount1| in raw token units (unsigned bigint as decimal string)
    ///
    /// Field 4: `amount1_abs`
    #[must_use]
    pub fn amount1_abs(&self) -> &'_ str {
        self.0.reborrow().amount1_abs
    }
    /// Token1 decimals (for display / volume scaling)
    ///
    /// Field 5: `token1_decimals`
    #[must_use]
    pub fn token1_decimals(&self) -> u32 {
        self.0.reborrow().token1_decimals
    }
    /// Token1 symbol (for labelling)
    ///
    /// Field 6: `token1_symbol`
    #[must_use]
    pub fn token1_symbol(&self) -> &'_ str {
        self.0.reborrow().token1_symbol
    }
}
impl ::core::convert::From<::buffa::OwnedView<SwapVolumeView<'static>>>
for SwapVolumeOwnedView {
    fn from(inner: ::buffa::OwnedView<SwapVolumeView<'static>>) -> Self {
        SwapVolumeOwnedView(inner)
    }
}
impl ::core::convert::From<SwapVolumeOwnedView>
for ::buffa::OwnedView<SwapVolumeView<'static>> {
    fn from(wrapper: SwapVolumeOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<SwapVolumeView<'static>>>
for SwapVolumeOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<SwapVolumeView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::SwapVolume {
    type View<'a> = SwapVolumeView<'a>;
    type ViewHandle = SwapVolumeOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct SwapVolumesView<'a> {
    /// Field 1: `swaps`
    pub swaps: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::SwapVolumeView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for SwapVolumesView<'a> {
    type Owned = super::super::SwapVolumes;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<super::super::__buffa::view::SwapVolumeView>(),
                )?;
                view.swaps
                    .push(
                        <super::super::__buffa::view::SwapVolumeView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::SwapVolumes, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::SwapVolumes, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::SwapVolumes {
            swaps: self
                .swaps
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for SwapVolumesView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.swaps {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.swaps {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for SwapVolumesView<'a> {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "SwapVolumes";
    const FULL_NAME: &'static str = "dex.volume.v1.SwapVolumes";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.SwapVolumes";
}
::buffa::impl_default_view_instance!(SwapVolumesView);
::buffa::impl_view_reborrow!(SwapVolumesView);
/** Self-contained, `'static` owned view of a `SwapVolumes` message.

 Wraps [`::buffa::OwnedView`]`<`[`SwapVolumesView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`SwapVolumesView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct SwapVolumesOwnedView(::buffa::OwnedView<SwapVolumesView<'static>>);
impl SwapVolumesOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SwapVolumesOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SwapVolumesOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::SwapVolumes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            SwapVolumesOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`SwapVolumesView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &SwapVolumesView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::SwapVolumes {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `swaps`
    #[must_use]
    pub fn swaps(
        &self,
    ) -> &::buffa::RepeatedView<'_, super::super::__buffa::view::SwapVolumeView<'_>> {
        &self.0.reborrow().swaps
    }
}
impl ::core::convert::From<::buffa::OwnedView<SwapVolumesView<'static>>>
for SwapVolumesOwnedView {
    fn from(inner: ::buffa::OwnedView<SwapVolumesView<'static>>) -> Self {
        SwapVolumesOwnedView(inner)
    }
}
impl ::core::convert::From<SwapVolumesOwnedView>
for ::buffa::OwnedView<SwapVolumesView<'static>> {
    fn from(wrapper: SwapVolumesOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<SwapVolumesView<'static>>>
for SwapVolumesOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<SwapVolumesView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::SwapVolumes {
    type View<'a> = SwapVolumesView<'a>;
    type ViewHandle = SwapVolumesOwnedView;
}
/// Per-pool token metadata, cached in a store keyed by pool address
/// (separate store keys per protocol to avoid cross-protocol collision)
#[derive(Clone, Debug, Default)]
pub struct TokenPairView<'a> {
    /// Field 1: `token0_address`
    pub token0_address: &'a str,
    /// Field 2: `token0_symbol`
    pub token0_symbol: &'a str,
    /// Field 3: `token0_decimals`
    pub token0_decimals: u32,
    /// Field 4: `token1_address`
    pub token1_address: &'a str,
    /// Field 5: `token1_symbol`
    pub token1_symbol: &'a str,
    /// Field 6: `token1_decimals`
    pub token1_decimals: u32,
}
impl<'a> ::buffa::MessageView<'a> for TokenPairView<'a> {
    type Owned = super::super::TokenPair;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.token0_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.token0_symbol = ::buffa::types::borrow_str(&mut cur)?;
            }
            3u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.token0_decimals = ::buffa::types::decode_uint32(&mut cur)?;
            }
            4u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.token1_address = ::buffa::types::borrow_str(&mut cur)?;
            }
            5u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.token1_symbol = ::buffa::types::borrow_str(&mut cur)?;
            }
            6u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::Varint,
                )?;
                view.token1_decimals = ::buffa::types::decode_uint32(&mut cur)?;
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::TokenPair, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::TokenPair, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::TokenPair {
            token0_address: self.token0_address.to_string(),
            token0_symbol: self.token0_symbol.to_string(),
            token0_decimals: self.token0_decimals,
            token1_address: self.token1_address.to_string(),
            token1_symbol: self.token1_symbol.to_string(),
            token1_decimals: self.token1_decimals,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for TokenPairView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, _cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.token0_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.token0_address) as u64;
        }
        if !self.token0_symbol.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.token0_symbol) as u64;
        }
        if self.token0_decimals != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.token0_decimals) as u64;
        }
        if !self.token1_address.is_empty() {
            size
                += 1u64
                    + ::buffa::types::string_encoded_len(&self.token1_address) as u64;
        }
        if !self.token1_symbol.is_empty() {
            size
                += 1u64 + ::buffa::types::string_encoded_len(&self.token1_symbol) as u64;
        }
        if self.token1_decimals != 0u32 {
            size
                += 1u64
                    + ::buffa::types::uint32_encoded_len(self.token1_decimals) as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        _cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.token0_address.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.token0_address, buf);
        }
        if !self.token0_symbol.is_empty() {
            ::buffa::types::put_string_field(2u32, &self.token0_symbol, buf);
        }
        if self.token0_decimals != 0u32 {
            ::buffa::types::put_uint32_field(3u32, self.token0_decimals, buf);
        }
        if !self.token1_address.is_empty() {
            ::buffa::types::put_string_field(4u32, &self.token1_address, buf);
        }
        if !self.token1_symbol.is_empty() {
            ::buffa::types::put_string_field(5u32, &self.token1_symbol, buf);
        }
        if self.token1_decimals != 0u32 {
            ::buffa::types::put_uint32_field(6u32, self.token1_decimals, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for TokenPairView<'a> {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "TokenPair";
    const FULL_NAME: &'static str = "dex.volume.v1.TokenPair";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.TokenPair";
}
::buffa::impl_default_view_instance!(TokenPairView);
::buffa::impl_view_reborrow!(TokenPairView);
/** Self-contained, `'static` owned view of a `TokenPair` message.

 Wraps [`::buffa::OwnedView`]`<`[`TokenPairView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`TokenPairView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct TokenPairOwnedView(::buffa::OwnedView<TokenPairView<'static>>);
impl TokenPairOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TokenPairOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TokenPairOwnedView(::buffa::OwnedView::decode_with_options(bytes, opts)?),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::TokenPair,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            TokenPairOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`TokenPairView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &TokenPairView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::TokenPair {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `token0_address`
    #[must_use]
    pub fn token0_address(&self) -> &'_ str {
        self.0.reborrow().token0_address
    }
    /// Field 2: `token0_symbol`
    #[must_use]
    pub fn token0_symbol(&self) -> &'_ str {
        self.0.reborrow().token0_symbol
    }
    /// Field 3: `token0_decimals`
    #[must_use]
    pub fn token0_decimals(&self) -> u32 {
        self.0.reborrow().token0_decimals
    }
    /// Field 4: `token1_address`
    #[must_use]
    pub fn token1_address(&self) -> &'_ str {
        self.0.reborrow().token1_address
    }
    /// Field 5: `token1_symbol`
    #[must_use]
    pub fn token1_symbol(&self) -> &'_ str {
        self.0.reborrow().token1_symbol
    }
    /// Field 6: `token1_decimals`
    #[must_use]
    pub fn token1_decimals(&self) -> u32 {
        self.0.reborrow().token1_decimals
    }
}
impl ::core::convert::From<::buffa::OwnedView<TokenPairView<'static>>>
for TokenPairOwnedView {
    fn from(inner: ::buffa::OwnedView<TokenPairView<'static>>) -> Self {
        TokenPairOwnedView(inner)
    }
}
impl ::core::convert::From<TokenPairOwnedView>
for ::buffa::OwnedView<TokenPairView<'static>> {
    fn from(wrapper: TokenPairOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<TokenPairView<'static>>>
for TokenPairOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<TokenPairView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::TokenPair {
    type View<'a> = TokenPairView<'a>;
    type ViewHandle = TokenPairOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct PoolTokenEntryView<'a> {
    /// Key = "\<protocol\>:\<pool_address\>" to ensure per-protocol namespacing
    ///
    /// Field 1: `key`
    pub key: &'a str,
    /// Field 2: `pair`
    pub pair: ::buffa::MessageFieldView<super::super::__buffa::view::TokenPairView<'a>>,
}
impl<'a> ::buffa::MessageView<'a> for PoolTokenEntryView<'a> {
    type Owned = super::super::PoolTokenEntry;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                view.key = ::buffa::types::borrow_str(&mut cur)?;
            }
            2u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                match view.pair.as_mut() {
                    Some(existing) => {
                        ::buffa::MessageView::merge_into_view(existing, sub, __sub_ctx)?
                    }
                    None => {
                        view.pair = ::buffa::MessageFieldView::set(
                            <super::super::__buffa::view::TokenPairView as ::buffa::MessageView>::decode_view_ctx(
                                sub,
                                __sub_ctx,
                            )?,
                        );
                    }
                }
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::PoolTokenEntry, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::PoolTokenEntry, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::PoolTokenEntry {
            key: self.key.to_string(),
            pair: match self.pair.as_option() {
                Some(v) => {
                    ::buffa::MessageField::<
                        super::super::TokenPair,
                        ::buffa::Inline<super::super::TokenPair>,
                    >::some(v.to_owned_from_source(__buffa_src)?)
                }
                None => ::buffa::MessageField::none(),
            },
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PoolTokenEntryView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        if !self.key.is_empty() {
            size += 1u64 + ::buffa::types::string_encoded_len(&self.key) as u64;
        }
        if self.pair.is_set() {
            let __slot = __cache.reserve();
            let inner_size = self.pair.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        if !self.key.is_empty() {
            ::buffa::types::put_string_field(1u32, &self.key, buf);
        }
        if self.pair.is_set() {
            ::buffa::types::put_len_delimited_header(
                2u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            self.pair.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for PoolTokenEntryView<'a> {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "PoolTokenEntry";
    const FULL_NAME: &'static str = "dex.volume.v1.PoolTokenEntry";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.PoolTokenEntry";
}
::buffa::impl_default_view_instance!(PoolTokenEntryView);
::buffa::impl_view_reborrow!(PoolTokenEntryView);
/** Self-contained, `'static` owned view of a `PoolTokenEntry` message.

 Wraps [`::buffa::OwnedView`]`<`[`PoolTokenEntryView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PoolTokenEntryView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PoolTokenEntryOwnedView(::buffa::OwnedView<PoolTokenEntryView<'static>>);
impl PoolTokenEntryOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolTokenEntryOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolTokenEntryOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::PoolTokenEntry,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolTokenEntryOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PoolTokenEntryView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PoolTokenEntryView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::PoolTokenEntry {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Key = "\<protocol\>:\<pool_address\>" to ensure per-protocol namespacing
    ///
    /// Field 1: `key`
    #[must_use]
    pub fn key(&self) -> &'_ str {
        self.0.reborrow().key
    }
    /// Field 2: `pair`
    #[must_use]
    pub fn pair(
        &self,
    ) -> &::buffa::MessageFieldView<super::super::__buffa::view::TokenPairView<'_>> {
        &self.0.reborrow().pair
    }
}
impl ::core::convert::From<::buffa::OwnedView<PoolTokenEntryView<'static>>>
for PoolTokenEntryOwnedView {
    fn from(inner: ::buffa::OwnedView<PoolTokenEntryView<'static>>) -> Self {
        PoolTokenEntryOwnedView(inner)
    }
}
impl ::core::convert::From<PoolTokenEntryOwnedView>
for ::buffa::OwnedView<PoolTokenEntryView<'static>> {
    fn from(wrapper: PoolTokenEntryOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PoolTokenEntryView<'static>>>
for PoolTokenEntryOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PoolTokenEntryView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::PoolTokenEntry {
    type View<'a> = PoolTokenEntryView<'a>;
    type ViewHandle = PoolTokenEntryOwnedView;
}
#[derive(Clone, Debug, Default)]
pub struct PoolTokenPairsView<'a> {
    /// Field 1: `entries`
    pub entries: ::buffa::RepeatedView<
        'a,
        super::super::__buffa::view::PoolTokenEntryView<'a>,
    >,
}
impl<'a> ::buffa::MessageView<'a> for PoolTokenPairsView<'a> {
    type Owned = super::super::PoolTokenPairs;
    fn decode_view(buf: &'a [u8]) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        let __limit = ::core::cell::Cell::new(::buffa::DEFAULT_UNKNOWN_FIELD_LIMIT);
        let __elem = ::core::cell::Cell::new(::buffa::DEFAULT_ELEMENT_MEMORY_LIMIT);
        <Self as ::buffa::MessageView>::decode_view_ctx(
            buf,
            ::buffa::DecodeContext::new(::buffa::RECURSION_LIMIT, &__limit)
                .with_element_memory(&__elem),
        )
    }
    fn decode_view_with_ctx(
        buf: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        <Self as ::buffa::MessageView>::decode_view_ctx(buf, ctx)
    }
    #[inline]
    fn merge_view_field(
        &mut self,
        tag: ::buffa::encoding::Tag,
        cur: &'a [u8],
        _before_tag: &'a [u8],
        ctx: ::buffa::DecodeContext<'_>,
    ) -> ::core::result::Result<&'a [u8], ::buffa::DecodeError> {
        let _ = ctx;
        #[allow(unused_variables)]
        let view = self;
        let mut cur = cur;
        match tag.field_number() {
            1u32 => {
                ::buffa::encoding::check_wire_type(
                    tag,
                    ::buffa::encoding::WireType::LengthDelimited,
                )?;
                let __sub_ctx = ctx.descend()?;
                let sub = ::buffa::types::borrow_bytes(&mut cur)?;
                ctx.register_element_memory(
                    ::core::mem::size_of::<
                        super::super::__buffa::view::PoolTokenEntryView,
                    >(),
                )?;
                view.entries
                    .push(
                        <super::super::__buffa::view::PoolTokenEntryView as ::buffa::MessageView>::decode_view_ctx(
                            sub,
                            __sub_ctx,
                        )?,
                    );
            }
            _ => {
                ::buffa::encoding::skip_field_depth(tag, &mut cur, ctx.depth())?;
            }
        }
        ::core::result::Result::Ok(cur)
    }
    fn to_owned_message(
        &self,
    ) -> ::core::result::Result<super::super::PoolTokenPairs, ::buffa::DecodeError> {
        self.to_owned_from_source(None)
    }
    #[allow(clippy::useless_conversion, clippy::needless_update)]
    fn to_owned_from_source(
        &self,
        __buffa_src: ::core::option::Option<&::buffa::bytes::Bytes>,
    ) -> ::core::result::Result<super::super::PoolTokenPairs, ::buffa::DecodeError> {
        #[allow(unused_imports)]
        use ::buffa::alloc::string::ToString as _;
        let _ = __buffa_src;
        ::core::result::Result::Ok(super::super::PoolTokenPairs {
            entries: self
                .entries
                .iter()
                .map(|v| v.to_owned_from_source(__buffa_src))
                .collect::<::core::result::Result<_, ::buffa::DecodeError>>()?,
            ..::core::default::Default::default()
        })
    }
}
impl<'a> ::buffa::ViewEncode<'a> for PoolTokenPairsView<'a> {
    #[allow(clippy::needless_borrow, clippy::let_and_return)]
    fn compute_size(&self, __cache: &mut ::buffa::SizeCache) -> u32 {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        let mut size = 0u64;
        for v in &self.entries {
            let __slot = __cache.reserve();
            let inner_size = v.compute_size(__cache);
            __cache.set(__slot, inner_size);
            size
                += 1u64 + ::buffa::encoding::varint_len(inner_size as u64) as u64
                    + inner_size as u64;
        }
        ::buffa::saturate_size(size)
    }
    #[allow(clippy::needless_borrow)]
    fn write_to(
        &self,
        __cache: &mut ::buffa::SizeCache,
        buf: &mut impl ::buffa::EncodeSink,
    ) {
        #[allow(unused_imports)]
        use ::buffa::Enumeration as _;
        for v in &self.entries {
            ::buffa::types::put_len_delimited_header(
                1u32,
                u64::from(__cache.consume_next()),
                buf,
            );
            v.write_to(__cache, buf);
        }
    }
}
impl<'a> ::buffa::MessageName for PoolTokenPairsView<'a> {
    const PACKAGE: &'static str = "dex.volume.v1";
    const NAME: &'static str = "PoolTokenPairs";
    const FULL_NAME: &'static str = "dex.volume.v1.PoolTokenPairs";
    const TYPE_URL: &'static str = "type.googleapis.com/dex.volume.v1.PoolTokenPairs";
}
::buffa::impl_default_view_instance!(PoolTokenPairsView);
::buffa::impl_view_reborrow!(PoolTokenPairsView);
/** Self-contained, `'static` owned view of a `PoolTokenPairs` message.

 Wraps [`::buffa::OwnedView`]`<`[`PoolTokenPairsView`]`<'static>>`: the decoded view and the [`::buffa::bytes::Bytes`] buffer it borrows from travel together, so the handle is `'static` and `Send + Sync` — suitable for async handlers, spawned tasks, and anywhere a `'static` bound is required.

 Field accessors return borrows tied to `&self`. Use [`Self::view`] to get the full [`PoolTokenPairsView`] when you need struct patterns, iteration helpers, or to pass the view to lifetime-parameterised code.*/
#[derive(Clone, Debug)]
pub struct PoolTokenPairsOwnedView(::buffa::OwnedView<PoolTokenPairsView<'static>>);
impl PoolTokenPairsOwnedView {
    /// Decode an owned view from a [`::buffa::bytes::Bytes`] buffer.
    ///
    /// The view borrows directly from the buffer's data; the buffer is
    /// retained inside the returned handle.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer contains invalid
    /// protobuf data.
    pub fn decode(
        bytes: ::buffa::bytes::Bytes,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolTokenPairsOwnedView(::buffa::OwnedView::decode(bytes)?),
        )
    }
    /// Decode with custom [`::buffa::DecodeOptions`] (recursion limit,
    /// max message size).
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError`] if the buffer is invalid or
    /// exceeds the configured limits.
    pub fn decode_with_options(
        bytes: ::buffa::bytes::Bytes,
        opts: &::buffa::DecodeOptions,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolTokenPairsOwnedView(
                ::buffa::OwnedView::decode_with_options(bytes, opts)?,
            ),
        )
    }
    /// Build from an owned message via an encode → decode round-trip.
    ///
    /// # Errors
    ///
    /// Returns [`::buffa::DecodeError::MessageTooLarge`] if the
    /// message's encoded size exceeds the 2 GiB protobuf limit, or
    /// another [`::buffa::DecodeError`] if the re-encoded bytes are
    /// somehow invalid (should not happen for well-formed messages).
    pub fn from_owned(
        msg: &super::super::PoolTokenPairs,
    ) -> ::core::result::Result<Self, ::buffa::DecodeError> {
        ::core::result::Result::Ok(
            PoolTokenPairsOwnedView(::buffa::OwnedView::from_owned(msg)?),
        )
    }
    /// Borrow the full [`PoolTokenPairsView`] with its lifetime tied to `&self`.
    #[must_use]
    pub fn view(&self) -> &PoolTokenPairsView<'_> {
        self.0.reborrow()
    }
    /// Convert to the owned message type.
    ///
    /// Infallible: this type's constructors wire-decode their
    /// buffer, and a view produced by wire decoding always
    /// converts. Delegates to [`::buffa::OwnedView::to_owned_message`],
    /// whose contract also governs handles converted from a raw
    /// [`::buffa::OwnedView`].
    #[must_use]
    pub fn to_owned_message(&self) -> super::super::PoolTokenPairs {
        self.0.to_owned_message()
    }
    /// The underlying bytes buffer.
    #[must_use]
    pub fn bytes(&self) -> &::buffa::bytes::Bytes {
        self.0.bytes()
    }
    /// Consume the handle, returning the underlying bytes buffer.
    #[must_use]
    pub fn into_bytes(self) -> ::buffa::bytes::Bytes {
        self.0.into_bytes()
    }
    /// Field 1: `entries`
    #[must_use]
    pub fn entries(
        &self,
    ) -> &::buffa::RepeatedView<
        '_,
        super::super::__buffa::view::PoolTokenEntryView<'_>,
    > {
        &self.0.reborrow().entries
    }
}
impl ::core::convert::From<::buffa::OwnedView<PoolTokenPairsView<'static>>>
for PoolTokenPairsOwnedView {
    fn from(inner: ::buffa::OwnedView<PoolTokenPairsView<'static>>) -> Self {
        PoolTokenPairsOwnedView(inner)
    }
}
impl ::core::convert::From<PoolTokenPairsOwnedView>
for ::buffa::OwnedView<PoolTokenPairsView<'static>> {
    fn from(wrapper: PoolTokenPairsOwnedView) -> Self {
        wrapper.0
    }
}
impl ::core::convert::AsRef<::buffa::OwnedView<PoolTokenPairsView<'static>>>
for PoolTokenPairsOwnedView {
    fn as_ref(&self) -> &::buffa::OwnedView<PoolTokenPairsView<'static>> {
        &self.0
    }
}
impl ::buffa::HasMessageView for super::super::PoolTokenPairs {
    type View<'a> = PoolTokenPairsView<'a>;
    type ViewHandle = PoolTokenPairsOwnedView;
}
