// @generated by buffa-codegen. DO NOT EDIT.
// source: entity.proto

pub mod value {
    #[allow(unused_imports)]
    use super::*;
    #[derive(Clone, PartialEq, Debug)]
    pub enum Typed {
        Int32(i32),
        Bigdecimal(::buffa::alloc::string::String),
        Bigint(::buffa::alloc::string::String),
        String(::buffa::alloc::string::String),
        Bytes(::buffa::alloc::vec::Vec<u8>),
        Bool(bool),
        Array(::buffa::alloc::boxed::Box<super::super::super::Array>),
    }
    impl ::buffa::Oneof for Typed {}
    impl From<super::super::super::Array> for Typed {
        fn from(v: super::super::super::Array) -> Self {
            Self::Array(::buffa::alloc::boxed::Box::new(v))
        }
    }
    impl From<super::super::super::Array> for ::core::option::Option<Typed> {
        fn from(v: super::super::super::Array) -> Self {
            Self::Some(Typed::from(v))
        }
    }
}
