// @generated by buffa-codegen. DO NOT EDIT.

include!("nft_mints.rs");
#[allow(
    non_camel_case_types,
    dead_code,
    unused_imports,
    unused_qualifications,
    clippy::derivable_impls,
    clippy::match_single_binding,
    clippy::uninlined_format_args,
    clippy::doc_lazy_continuation,
    clippy::module_inception
)]
pub mod __buffa {
    #[allow(unused_imports)]
    use super::*;
    pub mod view {
        #[allow(unused_imports)]
        use super::*;
        include!("nft_mints.__view.rs");
    }
    pub mod lazy_view {
        #[allow(unused_imports)]
        use super::*;
        include!("nft_mints.__lazy_view.rs");
    }
}
#[doc(inline)]
pub use self::__buffa::view::NftMintsView;
#[doc(inline)]
pub use self::__buffa::view::NftMintsOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::NftMintsLazyView;
#[doc(inline)]
pub use self::__buffa::view::NftMintView;
#[doc(inline)]
pub use self::__buffa::view::NftMintOwnedView;
#[doc(inline)]
pub use self::__buffa::lazy_view::NftMintLazyView;
